version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333" # HTTP API
      - "6334:6334" # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped

  app:
    build: .
    container_name: app
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - DEBUG=False
      - QDRANT__HOST=qdrant
    env_file:
      - .env
    depends_on:
      - qdrant
    restart: unless-stopped

volumes:
  qdrant_storage:
